// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4mgi_eP_9lGfrBIteNJWa__a2LRoRQNQ',
    appId: '1:1089198153938:android:84a6be8dff97c30c080d0b',
    messagingSenderId: '1089198153938',
    projectId: 'arched-sunbeam-478306-u3',
    storageBucket: 'arched-sunbeam-478306-u3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHAvKYxNKIBSQujcEPew4NFZQQ4XQ6Skg',
    appId: '1:1089198153938:ios:e38c625c2ad7335f080d0b',
    messagingSenderId: '1089198153938',
    projectId: 'arched-sunbeam-478306-u3',
    storageBucket: 'arched-sunbeam-478306-u3.firebasestorage.app',
    androidClientId: '1089198153938-04q35pvnoj4brdhvd738ov3ifa8vdbgs.apps.googleusercontent.com',
    iosClientId: '1089198153938-1gtlmm6q4ao6qsc2lm1g99fdh55jpijm.apps.googleusercontent.com',
    iosBundleId: 'com.example.hiddenPantryApp',
  );
}
